#!/bin/bash

#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright 2020 Joyent, Inc.
#

if [[ -n "$TRACE" ]]; then
	export PS4='[\D{%FT%TZ}] ${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
	set -o xtrace
else
	TRACE=
fi

set -euo pipefail
IFS=$'\n\t'

import_gpg_keys() {
	local file

	for file in $distrel/keys/*; do
		if [[ -f $file ]]; then
			found_key=true
			echo "Importing gpg key from $file"
			gpg --import $file
		fi
	done
	if [[ $found_key == false ]]; then
		echo "$0: Warning: no gpg key found in \
		    keys/$distro_l-$release" 1>&2
	fi

}

iso_file=
iso_sha=
iso_url=
get_iso_file_sha() {
	local file url
	# "" is a sentinal value
	local urls=("${ISO_URLS[@]}" "")

	if [[ -n $iso_file ]]; then
		return
	fi

	echo "Checking to see if we have the iso for $distro $release:"
	for url in "${ISO_URLS[@]}"; do
		for file in SHA256SUMS SHA256SUMS.sign; do
			wget -nv -O "$iso_dir/$file" "$url/$file"
		done
		gpg --verify $iso_dir/SHA256SUMS.sign

		# As new dot releases come out, the name of the iso file changes
		# according to a predictable pattern.  The sha256sums.txt file
		# contains the proper name.
		eval $(awk -v pattern="$DVD_PATTERN" '$2 ~ pattern {
			printf("iso_sha=%s; iso_file=%s;", $1, $2)
			exit 0
		    }' $iso_dir/SHA256SUMS)
		if [[ -n $iso_file ]]; then
			iso_url=$url
			return
		fi
	done

	echo "$0: unable to determine ISO file and/or sha256" 1>&2
	exit 1
}

fetch_iso() {
	local file sha out
	local need_iso=false
	local found_key=false

	if [[ ! -d $iso_dir ]]; then
		mkdir -p $iso_dir
	fi

	import_gpg_keys
	get_iso_file_sha

	echo "Checking integrity of $iso_file"
	if [[ ! -f $iso_dir/$iso_file ]]; then
		echo "No local copy of $iso_file. Fetching latest $iso_file"
		need_iso=true
	elif ! echo $iso_sha $iso_dir/$iso_file | sha256sum -c -; then
		echo "Local copy of $iso_file is bad." \
		    "Fetching latest $iso_file."
		rm -f "$iso_dir/$iso_file"
		need_iso=true
	fi

	if $need_iso; then
		wget -nv -O "$iso_dir/$iso_file" "$iso_url/$iso_file"
		echo "Checking integrity of $iso_dir/$iso_file"
		echo "$iso_sha" "$iso_dir/$iso_file" | sha256sum -c -
	fi
}

mount_iso() {
	local file=$1
	local mntpt=$2

	# Check if $mntpt is already mounted
	# This may happen if a previous build failed
	if df -h "$mntpt" 2>/dev/null | grep -qw "$mntpt"; then
		echo "Unmounting $mntpt from previous build..."
		umount "$mntpt"
	fi

	echo "Mounting $file to $mntpt"
	if [[ ! -d $mntpt ]]; then
		echo "Creating $mntpt..."
		mkdir -p "$mntpt"
	fi
	case $(uname -s) in
		Linux)
			mount "$file" "$mntpt" -o loop
			;;
		SunOS)
			mount -F hsfs "$file" "$mntpt"
			;;
		*)
			echo "$0: do not know how to mount an iso on" \
			    "$(uname -s)". 1>&2
			exit 2
			;;
	esac
}

create_iso_root() {
	local src_mntpt=/tmp/mnt/$distrel

	mount_iso "$iso_dir/$iso_file" "$src_mntpt"

	echo "Creating ISO Layout"

	if [[ -d $iso_root ]]; then
		echo "Layout $iso_root exists...nuking"
		rm -rf "$iso_root"
	fi
	echo "Creating $iso_root"
	mkdir -p "$iso_root"

	echo "Copying distribution ISO to $iso_root"
	(cd "$src_mntpt" && find . | cpio -pd "$iso_root")

	umount "$src_mntpt"
}

copy_guest_tools() {
	echo "Copying $guesttools"
	echo "Initiallizing and fetching submodule $guesttools"
	git submodule update --init
	cp -R ./$guesttools/ $iso_root/
}

create_iso() {
	echo "Preparing installer ISO"
	create_iso_root
	copy_guest_tools

	cp "$distrel/preseed.cfg" "$iso_root/preseed.cfg"
	cp "$distrel/early-command" "$iso_root/early-command"
	cp "$distrel/late-command" "$iso_root/late-command"

	echo "Creating installer ISO"
	local volume="$(isoinfo -d -i "$iso_file" | grep "^Volume id:" |
	    sed 's/Volume id: //')"
	# This ISO is not bootable.  Rather than futzing with the isolinux
	# configuration, we just pass boot pargs via qemu.
	mkisofs -r -R -J -T -v -V "$volume" -A "$volume" -o "$iso" "$iso_root"
	echo "Installer ISO $iso is ready"
}

create_image() {
	local desc
	local media_mntpt=/tmp/mnt/$distrel-media
	local qemu_args=()
	local append=

	get_iso_file_sha

	append+=" net.ifnames=0 biosdevname=0"
	append+=" priority=high file=/cdrom/preseed.cfg locale=en_US"
	append+=" keymap=us"
	qemu_args+=( "-kernel" "$iso_root/install.amd/vmlinuz" )
	qemu_args+=( "-initrd" "$iso_root/install.amd/initrd.gz" )
	qemu_args+=( "-append" "$append" )

	desc="$distro $release 64-bit image with just essential packages "
	desc+="installed. Built to run on bhyve or KVM virtual machines."

	local stamp=$branch-${cur_time//[:-]}-$githash
	$top/eng/tools/create-hybrid-image -i "$iso" \
		-n "$distrel" -d "$desc" -p "$top/imgmanifest.in" \
		-o "$top/bits/$distrel/$stamp" \
		-u "https://docs.joyent.com/images/linux/$distro" \
		-- "${qemu_args[@]}" 2>&1 | tee $distrel-qemu.log

	# Verify that any JOYENT_STATUS_* items are all ok.  Ideally this would
	# run before create-hybrid-image bothers with the zfs send.  Even though
	# it is running a bit late here, it will prevent Jenkins from calling a
	# build good
	local have var val fail
	fail=false
	typeset -A have
	for var in "${JOYENT_STATUS_VARS[@]}"; do
		have["$var"]='<nothing>'
	done
	eval $(grep "^JOYENT_STATUS_" $distrel-qemu.log | awk -F= \
	    '{gsub("\r", "", $2); printf("have['%s']='%s'\n", $1, $2)}')
	for var in "${JOYENT_STATUS_VARS[@]}"; do
		val=${have[$var]}
		if [[ "$val" != 'ok' ]]; then
			echo "Error: expected $var=ok, got $var=$val" 1>&2
			fail=true
		else
			echo "Ok: got $var=$val"
		fi
		unset have["$var"]
	done
	for var in "${!have[@]}"; do
		val=${have[$var]}
		echo "Error: unexpected $var=$val" 1>&2
		fail=true
	done

	if [[ $fail == true ]]; then
		exit 1
	fi

	# All is well - let future invocations of upload_image know.
	echo "$stamp" > $top/bits/$distrel-latest-build-stamp
}

upload_image() {
	local bits=bits

	if [[ ! -f $bits/$distrel-latest-build-stamp ]]; then
		echo "Error: no latest build" 2>&1
		exit 1
	fi
	local stamp=$(cat $bits/$distrel-latest-build-stamp)

	local publish=
	if [[ -f /root/opt/imgapi-cli/bin/updates-imgadm ]]; then
		publish=-p
	fi
	$top/eng/tools/bits-upload.sh $publish -b "$branch" \
	    -D "$bits/$distrel/$stamp" \
	    -d "/public/builds/$distrel" \
	    -n "$distrel" \
	    -t "$stamp"

	local manta_url=${MANTA_URL:-https://us-east.manta.joyent.com}
	local manta_path=${MANTA_USER:-Joyent_Dev}/public/builds/$distrel
	local file path
	find $bits/$distrel/$stamp -name \*.zfs.gz -o -name \*.imgmanifest |
		while read file; do
			path="/$manta_path/$stamp/$(basename $file)"
			echo "$path"
			echo "$manta_url/$path"
			echo ""
		done > $distrel.artifacts-in-manta
}


usage() {
	cat <<EOF
Usage:
	$0 [options] [command ...]
option:
	-h	This message
	-r	Debian release
	-R	Full release (e.g. 10.1.0)

Commands:
	fetch	Fetch the installation ISO
	iso	Create a installer ISO
	image	Generate the image

If no command is given, all commands are run in the appropriate order.
EOF
}

typeset -l distro_l=debian
distro=Debian
release=

while getopts :hr: opt; do
	case "$opt" in
	r)	release=$OPTARG
		;;
	h)
		usage;
		exit 0
		;;
	\?)
		echo "$0: Invalid option $OPTARG" 1>&2
		usage 1>&2
		exit 1
		;;
	*)
		echo "$0: BUG: unhandled option $opt" 1>&2
		exit 2
		;;
	esac
done

shift $(( OPTIND - 1 ))

if [[ -z $release ]]; then
	echo "$0: must specify $distro release with -r" 1>&2
	exit 1
fi

cur_time=$(date +%FT%TZ)
top=$(cd "$(dirname $0)" && pwd -P)
distrel=$distro_l-$release
iso_root=$top/$distrel/root
iso_dir=/data/mi-centos-hvm/fetched-iso/$distrel
# The iso file generated by create_iso
iso=$top/$distrel-joyent.iso
guesttools=sdc-vmtools

branch=$(git describe --all | sed -e 's,^heads/,,' -e 's,/,_,g')
githash="$(git log -n 1 --pretty=format:%h)"

DVD_PATTERN=^$distro_l-$release\.[0-9]+\.[0-9]+-amd64-netinst\.iso$
ISO_URLS=(
    https://cdimage.debian.org/cdimage/release/current/amd64/iso-cd/
    https://cdimage.debian.org/cdimage/archive/latest-oldstable/amd64/iso-cd/
    https://cdimage.debian.org/cdimage/archive/latest-oldoldstable/amd64/iso-cd/
)
# Each of these are expected to be set to "ok" in output from guest
JOYENT_STATUS_VARS=( JOYENT_STATUS_PRE JOYENT_STATUS_POST )

fail=false
for cmd in wget gpg mkisofs; do
	if ! type -path $cmd >/dev/null; then
		fail=true
		echo "$0: command $cmd not found" 1>&2
	fi
done

if (( $(ps -o uid= -p $$) != 0 )); then
	fail=true
	echo "$0: must be root" 1>&2
fi
$fail && exit 1

if [[ -f $distrel/create-image-overrides.sh ]]; then
	. $distrel/create-image-overrides.sh
fi

if (( $# == 0 )); then
	set -- fetch iso image
fi

for arg in "$@"; do
	case $arg in
	fetch)
		fetch_iso
		;;
	iso)
		create_iso
		;;
	image)
		create_image
		;;
	upload)
		upload_image
		;;
	esac
done
